# Generated by Django 3.0.5 on 2020-04-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200429_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='guestuserlog',
            old_name='guest_user_id',
            new_name='guest_user',
        ),
        migrations.RenameField(
            model_name='guestuserlog',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='usersearchlog',
            old_name='guest_user_id',
            new_name='guest_user',
        ),
        migrations.RenameField(
            model_name='uservote',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='uservote',
            old_name='guest_user_id',
            new_name='guest_user',
        ),
        migrations.RenameField(
            model_name='uservote',
            old_name='question_id',
            new_name='question',
        ),
    ]
